config/routes.rb
Rails.application.routes.draw do

  devise_for :employees

  root 'home#cash_book'

  get '/daily_status', to: 'home#daily_status'
  get '/cash_book', to: 'home#cash_book'
  get '/close_previous_month', to: 'home#close_previous_month'

  resources :daily_closings

  resources :departments do
    get :switch, on: :member
    get :initial_balance, on: :member
    put :update_balance, on: :member
  end

  resources :employees do
    post :add, on: :collection
    put :update_info, on: :member
    get :change_password, on: :member
    put :update_password, on: :member
  end

  namespace :expenses do
    resources :categories
    resources :expenses do
      get :monthly_report, on: :collection
      get :yearly_report, on: :collection
      get :report_breakdown, on: :collection
    end
  end

  namespace :inventory do
    namespace :suppliers do
      resources :suppliers
      resources :orders
      resources :payments
    end
    namespace :customers do
      resources :customers
      resources :orders
      resources :payments
    end
    resources :parties do
      get :balance_report, on: :collection
      post :import, on: :collection
    end
    resources :products do
      get :get_details, on: :member
      get :stock_report, on: :collection
      post :import, on: :collection
    end
    resources :product_categories do
      get :product_sub_categories, on: :member
    end
    resources :deposit_categories
    resources :deposits
    resources :product_replacements do
      get :receive, on: :member
      get :reject_product, on: :member
    end
    resources :withdraw_categories
    resources :withdraws
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:user_login]

  attr_accessor :user_login

  mount_uploader :image, ImageUploader

  belongs_to :department
  has_many :suppliers_payments, :class_name => 'Inventory::Suppliers::Payment'
  has_many :customers_payments, :class_name => 'Inventory::Customers::Payment'
  has_many :suppliers_orders, :class_name => 'Inventory::Suppliers::Order'
  has_many :customers_orders, :class_name => 'Inventory::Customers::Order'

  def user_login(user_login)
    @user_login = user_login
  end

  def user_login
    @user_login || self.user_name || self.email
  end

  def update_without_password(params, *options)
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  protected

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:user_login)
      where(conditions.to_h).where(["lower(user_name) = :value OR lower(email) = :value", {:value => login.downcase}]).first
    elsif conditions.has_key?(:user_name) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update_info, :destroy, :show, :update_password, :change_password]

  def index
    @employees = current_department.employees.where(is_active: true)
  end

  def show
    respond_to do |format|
      format.js
    end
  end

  def new
    @employee = Employee.new
  end

  def add
    @employee = current_department.employees.build(employee_params)
    @employee.role = AppSetting::EMPLOYEE_ROLE[:staff]
    respond_to do |format|
      if @employee.save
        format.html {redirect_to employees_path, notice: 'Employee successfully created'}
      else
        format.html { render :new, danger: "Employee couldn't be created" }
      end
    end
  end

  def edit
  end

  def update_info
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_path, notice: "Employee was successfully created" }
      else
        format.html { redirect_to employees_path, notice: "Employee couldn't be updated" }
      end
    end
  end

  def change_password
  end

  def update_password
    respond_to do |format|
      if @employee.update_without_password(employee_params)
        if @employee == current_employee
          sign_out @employee
        end
        format.html { redirect_to employees_path, success: 'You have changed your password successfully.' }
      else
        format.html { redirect_to :back, notice: "#{ errors_to_message_string(@employee.errors) }" }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @employee == current_employee
        format.html { redirect_to employees_path, notice: 'You can not delete yourself.' }
      else
        @employee.destroy!
        format.html { redirect_to employees_path, notice: 'Successfully deleted' }
      end
    end
  end

  private
  def set_employee
    @employee = Employee.find_by_id(params[:id])
  end

  def employee_params
    params.require(:employee).permit!
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_edit_employee.html.erb
<%= form_for @employee, url: update_info_employee_path(@employee), html: {method: :put, id: 'employee-addition-form'} do |f| %>
    <div class="col-md-12">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :role %>
          <%= f.select :role, options_for_select(AppSetting::EMPLOYEE_ROLE.collect{|k,v| [v, v]}, f.object.role), {}, {class: "form-control"} %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :gender, 'Gender' %>
          <%= f.select :gender, options_for_select(['Male', 'Female']), {}, {class: "form-control"} %>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :phone %>
          <%= f.text_field :phone, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :address %>
          <%= f.text_area :address, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :user_name %>
          <%= f.text_field :user_name, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="col-md-12">
        <div class="pull-right">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
<% end %>

app/views/employees/_employee_detail.html.erb
<%= render 'shared/modal_header', title: 'Employee Detail' %>

<div class="modal-body">
  <%= image_tag(@employee.image.url(:thumb)) %>
  <h4>Role</h4>
  <%= @employee.role %>
  <h4>Name</h4>
  <%= @employee.name %>
  <h4>User Name</h4>
  <%= @employee.user_name %>
  <h4>Email</h4>
  <%= @employee.email %>
  <h4>Phone</h4>
  <%= @employee.phone %>
  <h4>Gender</h4>
  <%= @employee.gender %>
  <h4>Address</h4>
  <%= @employee.address %>
</div>

<div class="modal-footer clearfix">
  <div class="pull-right">
    <div class='btn btn-default' data-dismiss="modal">Close</div>
  </div>
</div>

app/views/employees/_employee_row.html.erb
<tr>
  <td><%= employee.name %></td>
  <td><%= employee.email %></td>
  <td><%= employee.address %></td>
  <td>
    <%= link_to 'change password', change_password_employee_path(employee) %>
    <%= link_to employee_path(employee), class: 'btn info-color', remote: true do %>
        <i class="fa fa-eye"> </i>
    <% end %>
    <%= link_to edit_employee_path(employee), class: 'btn warning-color' do %>
        <i class="fa fa-pencil"> </i>
    <% end %>
    <%= link_to employee_path(employee), method: :delete, class: 'btn danger-color', data: {confirm: "Are you sure?"} do %>
        <i class="fa fa-times"> </i>
    <% end %>
  </td>
</tr>

app/views/employees/_form.html.erb
<%= form_for @employee, url: add_employees_path,  html:{id: 'employee-addition-form'} do |f| %>
    <div class="col-md-12">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :role %>
          <%= f.select :role, options_for_select(AppSetting::EMPLOYEE_ROLE.collect{|k,v| [v, v]}, f.object.role), {}, {class: "form-control"} %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :gender, 'Gender' %>
          <%= f.select :gender, options_for_select(['Male', 'Female']), {}, {class: "form-control"} %>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :phone %>
          <%= f.text_field :phone, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :address %>
          <%= f.text_area :address, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :user_name %>
          <%= f.text_field :user_name, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="col-md-12">
        <div class="pull-right">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
<% end %>

app/views/employees/change_password.html.erb
<div class="row reset-padding">
  <div class="content-wrapper">
    <div class="header-wrapper">
      <h4>
        Change Password of <%= @employee.name %>
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper">
      <div class="row content-body">
        <div class="auth-form-wrapper">
          <%= form_for(@employee, url: update_password_employee_path(@employee), html: {method: :put, id: 'update-password', role:'form' }) do |f| %>
              <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, class: "form-control" %>
              </div>

              <div class="pull-right">
                <%= f.submit "Submit", class: 'btn btn-primary' %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/edit.html.erb
<div class="row reset-padding">
  <div class="content-wrapper">
    <div class="header-wrapper">
      <h4>
        Edit Employee
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper">
      <div class="row content-body">
        <%= render 'edit_employee' %>
      </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="row reset-padding">
  <div class="content-wrapper">
    <div class="header-wrapper">
      <h4>
        Employees
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper">
      <div class="row actions-button">
        <%= link_to new_employee_path, class: 'btn btn-default pull-right' do %>
            <i class="fa fa-plus-circle"></i> Add New Employee
        <% end %>
      </div>
      <div class="row content-body">
        <table class="table beaccount-table action-table table-responsive table-hover table-striped">
          <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Address</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @employees.each do |employee| %>
              <%= render 'employee_row', employee: employee %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="row reset-padding">
  <div class="content-wrapper">
    <div class="header-wrapper">
      <h4>
        New Employee
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper">
      <div class="row content-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/employees/show.js.erb
$('#global-modal').modal({backdrop: 'static', keyboard: false});
$('#global-modal').modal('show').find('.modal-content').html("<%= escape_javascript(render 'employee_detail').html_safe %>");