config/routes.rb
Rails.application.routes.draw do

  devise_for :employees

  root 'home#cash_book'

  get '/daily_status', to: 'home#daily_status'
  get '/cash_book', to: 'home#cash_book'
  get '/close_previous_month', to: 'home#close_previous_month'

  resources :daily_closings

  resources :departments do
    get :switch, on: :member
    get :initial_balance, on: :member
    put :update_balance, on: :member
  end

  resources :employees do
    post :add, on: :collection
    put :update_info, on: :member
    get :change_password, on: :member
    put :update_password, on: :member
  end

  namespace :expenses do
    resources :categories
    resources :expenses do
      get :monthly_report, on: :collection
      get :yearly_report, on: :collection
      get :report_breakdown, on: :collection
    end
  end

  namespace :inventory do
    namespace :suppliers do
      resources :suppliers
      resources :orders
      resources :payments
    end
    namespace :customers do
      resources :customers
      resources :orders
      resources :payments
    end
    resources :parties do
      get :balance_report, on: :collection
      post :import, on: :collection
    end
    resources :products do
      get :get_details, on: :member
      get :stock_report, on: :collection
      post :import, on: :collection
    end
    resources :product_categories do
      get :product_sub_categories, on: :member
    end
    resources :deposit_categories
    resources :deposits
    resources :product_replacements do
      get :receive, on: :member
      get :reject_product, on: :member
    end
    resources :withdraw_categories
    resources :withdraws
  end
end

app/views/shared/_flash_message.html.erb
<script type="text/javascript">
    $(function () {
        <% flash.each do |name, msg| -%>
        popupMessage("<%=raw msg %>", "<%= flash_types.include?(name)  ? "alert-#{ name }" : "alert-info" %>");
        <% end -%>
        <% flash.clear %>
    });
</script>

app/views/shared/_header.html.erb
<div class="main-menu clearfix ">
  <ul>
    <li> <%= link_to 'Home', root_path %> </li>
  </ul>
  <ul class="pull-right mobile-menu">
    <li>
      <a class="mobile-menu-toggle" href="#">
        <i class="fa fa-bars"></i>
      </a>
    </li>
  </ul>
  <ul class="pull-right desktop-menu">
    <% if employee_signed_in? %>
        <li class="top-menu-dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Employee
          </a>
          <ul class="top-menu-dropdown-content">
            <li>
              <%= link_to 'Employee List', employees_path %>
            </li>
          </ul>
        </li>
        <li class="top-menu-dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown">
            Inventory
          </a>
          <ul class="top-menu-dropdown-content">
            <li> <%= link_to 'Product Category', inventory_product_categories_path %></li>
            <li> <%= link_to 'Products', inventory_products_path %></li>
            <li> <%= link_to 'Parties', inventory_parties_path %></li>
            <li> <%= link_to 'Purchase Order', inventory_suppliers_orders_path %></li>
            <li> <%= link_to 'Sale Order', inventory_customers_orders_path %></li>
            <li> <%= link_to 'Product Replacements', inventory_product_replacements_path %></li>
          </ul>
        </li>
        <li class="top-menu-dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown">
            Payment
          </a>
          <ul class="top-menu-dropdown-content">
            <li> <%= link_to 'Supplier Payments', inventory_suppliers_payments_path %></li>
            <li> <%= link_to 'Customer Payments', inventory_customers_payments_path %></li>
          </ul>
        </li>
        <li class="top-menu-dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown">
            Deposit
          </a>
          <ul class="top-menu-dropdown-content">
            <li> <%= link_to 'Deposit Category', inventory_deposit_categories_path %></li>
            <li> <%= link_to 'Deposit', inventory_deposits_path %></li>
          </ul>
        </li>
        <li class="top-menu-dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown">
            Withdraw
          </a>
          <ul class="top-menu-dropdown-content">
            <li> <%= link_to 'Withdraw Category', inventory_withdraw_categories_path %></li>
            <li> <%= link_to 'Withdraw', inventory_withdraws_path %></li>
          </ul>
        </li>
        <li class="top-menu-dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown">
            Expense
          </a>
          <ul class="top-menu-dropdown-content">
            <li> <%= link_to 'Categories', expenses_categories_path %></li>
            <li> <%= link_to 'Expenses', expenses_expenses_path %></li>
            <li> <%= link_to 'Monthly Report', monthly_report_expenses_expenses_path %></li>
            <li> <%= link_to 'Yearly Report', yearly_report_expenses_expenses_path %></li>
          </ul>
        </li>
        <!--<li class="top-menu-dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown">Switch department</a>
          <ul class="top-menu-dropdown-content last-dropdown">
            <%# departments.each do |department| %>
                <li class="<%#= current_department == department ? 'current-department' : '' %>">
                  <%#= link_to switch_department_path(department) do %>
                      <%#= department.name %>
                  <%# end %>
                </li>
            <%# end %>
          </ul>
        </li>-->
        <!--<li class="top-menu-dropdown">
          <a class="dropdown-toggle" href="#" data-toggle="dropdown">
            <i class="fa fa-sign-out"></i>
          </a>

          <ul class="top-menu-dropdown-content last-dropdown">
            <li>
              <%#= link_to departments_path do %>
                  <i class="fa fa-sign-out"></i> Departmets
              <%# end %>
            </li>
          </ul>
        </li>-->
        <li class="top-menu-dropdown">
          <a class="dropdown-toggle" href="#" data-toggle="dropdown">
            <i class="fa fa-user"></i>
          </a>

          <ul class="top-menu-dropdown-content last-dropdown">
            <li>
              <%= link_to initial_balance_department_path(current_department) do %>
                  <i class="fa fa-usd"></i> Initial Balance
              <% end %>
            </li>
            <li>
              <%= link_to destroy_employee_session_path, :method => :delete do %>
                  <i class="fa fa-sign-out"></i> Logout
              <% end %>
            </li>
          </ul>
        </li>
    <% end %>
  </ul>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="global-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content modal-body">

    </div>
  </div>
</div>

app/views/shared/_modal_header.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title"><%= title %>  </h4>
</div>

app/views/shared/_no_data_found.html.erb
<div id='no-data-found' class="alert alert-info text-center mb0">
  <h3 class="mt10"><%= message %></h3>
</div>

app/views/shared/_notification.html.erb
<div id='notification' class="">
  <a id="notice-close" href="#" class="close" aria-label="close">×</a>
  <p id="flash-msg-text" class="mr20"></p>
</div>