config/routes.rb
Rails.application.routes.draw do

  devise_for :employees

  root 'home#cash_book'

  get '/daily_status', to: 'home#daily_status'
  get '/cash_book', to: 'home#cash_book'
  get '/close_previous_month', to: 'home#close_previous_month'

  resources :daily_closings

  resources :departments do
    get :switch, on: :member
    get :initial_balance, on: :member
    put :update_balance, on: :member
  end

  resources :employees do
    post :add, on: :collection
    put :update_info, on: :member
    get :change_password, on: :member
    put :update_password, on: :member
  end

  namespace :expenses do
    resources :categories
    resources :expenses do
      get :monthly_report, on: :collection
      get :yearly_report, on: :collection
      get :report_breakdown, on: :collection
    end
  end

  namespace :inventory do
    namespace :suppliers do
      resources :suppliers
      resources :orders
      resources :payments
    end
    namespace :customers do
      resources :customers
      resources :orders
      resources :payments
    end
    resources :parties do
      get :balance_report, on: :collection
      post :import, on: :collection
    end
    resources :products do
      get :get_details, on: :member
      get :stock_report, on: :collection
      post :import, on: :collection
    end
    resources :product_categories do
      get :product_sub_categories, on: :member
    end
    resources :deposit_categories
    resources :deposits
    resources :product_replacements do
      get :receive, on: :member
      get :reject_product, on: :member
    end
    resources :withdraw_categories
    resources :withdraws
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:department_id] = current_department.id
  end

  def cash_book
    @date = params[:date].present? ? Date.parse(params[:date]) : Date.today

    @customer_credit_orders = current_department.sale_orders.where(is_cash: false, date: @date)
    @supplier_credit_orders = current_department.purchase_orders.where(is_cash: false, date: @date)
    @customer_cash_orders = current_department.sale_orders.where(is_cash: true, date: @date)
    @customer_credit_payments = current_department.customers_payments.where(is_cash: false, date: @date)
    @supplier_credit_payments = current_department.suppliers_payments.where(is_cash: false, date: @date)

    @cash_outs = Department.get_daily_cash_outs(current_department, @date)

    @cash_in = 0.0
    @cash_out = 0.0

    @daily_closing = DailyClosing.find_by_date(@date)
    @tomorrow_closing = DailyClosing.find_by_date(@date - 1.day)

    if @tomorrow_closing.present?
      @initial_balance = @tomorrow_closing.balance
    else
      department_date = current_department.created_at.strftime('%Y-%m-%d').to_date
      if @date == department_date
        @initial_balance = current_department.balance
      end
    end

    unless @daily_closing.present?
      @daily_closing = DailyClosing.new
    end

    @is_monthly_closing = false
    unless @date.month == current_department.month
      closed_products = ProductsMonthlyClosing.where(month: (@date.beginning_of_month - 1.day).month, year: (@date.beginning_of_month - 1.day).year)
      @is_monthly_closing = closed_products.present? ? false : true
    end
  end

  def close_previous_month
    ProductsMonthlyClosing.close
    PartiesMonthlyClosing.close
    respond_to do |format|
      format.html{ redirect_to cash_book_path(), notice: 'Successfully closed.'}
    end
  end

  def daily_status
    date = Date.today


    #**********************Supplier************************#
    @suppliers_data = []
    purchase_orders = current_department.purchase_orders#.where(date: date)
    purchase_orders.each do |order|
      @suppliers_data.push({type: 'Order', id: order.id, party_id: order.party_id, party_name: order.party.name, amount: order.total, method: order.method, created_at: order.created_at})
    end
    suppliers_payments = current_department.suppliers_payments#.where(date: date)
    suppliers_payments.each do |payment|
      @suppliers_data.push({type: 'Payment', id: payment.id, party_id: payment.party_id, party_name: payment.party.name, amount: payment.amount, method: payment.method, created_at: payment.created_at})
    end
    @suppliers_data.sort_by! {|data| data[:created_at]}


    #**********************Customer************************#
    @customer_data = []
    sales_orders = current_department.sale_orders#.where(date: date)
    sales_orders.each do |order|
      @customer_data.push({type: 'Order', id: order.id, party_id: order.party_id, party_name: order.party.name, amount: order.total, method: order.method, created_at: order.created_at})
    end
    customers_payments = current_department.customers_payments#.where(date: date)
    customers_payments.each do |payment|
      @customer_data.push({type: 'Payment', id: payment.id, party_id: payment.party_id, party_name: payment.party.name, amount: payment.amount, method: payment.method, created_at: payment.created_at})
    end
    @customer_data.sort_by! {|data| data[:created_at]}


    # @suppliers_data.each do |data|
    #   puts data.inspect
    # end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_cash_outs.html.erb
<table class="table beaccount-table table-responsive table-hover table-striped cashbook-table">
  <thead>
  <tr>
    <th colspan="3">Cash Outs</th>
  </tr>
  <tr>
    <th>Name</th>
    <th>Amount</th>
    <th>Quantity</th>
  </tr>
  </thead>
  <tbody>
  <% total = 0.0 %>
  <% @cash_outs.each do |data| %>
      <tr>
        <td>
          <%= data[:name] %>
        </td>
        <td>
          <%= data[:amount] %>
          <% total += data[:amount] %>
        </td>
        <td>
          <%= data[:quantity] %>
        </td>
      </tr>
  <% end %>
  <tr>
    <td><b>Total</b></td>
    <td><b><%= total %></b></td>
    <td><b></b></td>
  </tr>
  <% @cash_out += total %>
  </tbody>
</table>

app/views/home/_cash_sales.html.erb
<table class="table beaccount-table table-responsive table-hover table-striped cashbook-table">
  <thead>
  <tr>
    <th colspan="3">Cash Sale</th>
  </tr>
  <tr>
    <th>Product</th>
    <th>Amount</th>
    <th>Quantity</th>
  </tr>
  </thead>
  <tbody>
  <% total = 0.0 %>
  <% @customer_cash_orders.each do |order| %>
      <% order.order_items.each do |order_item| %>
          <tr>
            <td>
              <%= order_item.product.name if order_item.product.present? %>
            </td>
            <td>
              <%= order_item.total %>
              <% total += order_item.total %>
            </td>
            <td>
              <%= order_item.quantity %>
            </td>
          </tr>
      <% end %>
  <% end %>
  <tr>
    <td><b>Total</b></td>
    <td><b><%= total %></b></td>
    <td><b></b></td>
  </tr>
  <% @cash_in += total %>
  </tbody>
</table>

app/views/home/_credit_purchases.html.erb
<table class="table beaccount-table table-responsive table-hover table-striped cashbook-table">
  <thead>
  <tr>
    <th colspan="3">Credit Purchase</th>
  </tr>
  <tr>
    <th>Party</th>
    <th>Amount</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% total = 0.0 %>
  <% @supplier_credit_orders.each do |order| %>
      <tr>
        <td>
          <%= order.party.name if order.party.present? %>
        </td>
        <td>
          <%= order.total %>
          <% total += order.total %>
        </td>
        <td>
          <%= link_to inventory_suppliers_order_path(order), class: 'btn info-color' do %>
              <i class="fa fa-eye"> </i>
          <% end %>
        </td>
      </tr>
  <% end %>
  <tr>
    <td><b>Total</b></td>
    <td><b><%= total %></b></td>
    <td><b></b></td>
  </tr>
  </tbody>
</table>

app/views/home/_credit_sales.html.erb
<table class="table beaccount-table table-responsive table-hover table-striped cashbook-table">
  <thead>
  <tr>
    <th colspan="3">Credit Sales</th>
  </tr>
  <tr>
    <th>Party</th>
    <th>Amount</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% total = 0.0 %>
  <% @customer_credit_orders.each do |order| %>
      <tr>
        <td>
          <%= order.party.name if order.party.present? %>
        </td>
        <td>
          <%= order.total %>
          <% total += order.total %>
        </td>
        <td>
          <%= link_to inventory_customers_order_path(order), class: 'btn info-color' do %>
              <i class="fa fa-eye"> </i>
          <% end %>
        </td>
      </tr>
  <% end %>
  <tr>
    <td><b>Total</b></td>
    <td><b><%= total %></b></td>
    <td><b></b></td>
  </tr>
  </tbody>
</table>

app/views/home/_customer_payments.html.erb
<table class="table beaccount-table table-responsive table-hover table-striped cashbook-table">
  <thead>
  <tr>
    <th colspan="3">Customer Payments</th>
  </tr>
  <tr>
    <th>Party</th>
    <th>Amount</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% total = 0.0 %>
  <% @customer_credit_payments.each do |payment| %>
      <tr>
        <td>
          <%= payment.party.name if payment.party.present? %>
        </td>
        <td>
          <%= payment.total %>
          <% total += payment.total %>
        </td>
        <td>
          <%= link_to inventory_customers_payment_path(payment), class: 'btn info-color', remote: true do %>
              <i class="fa fa-eye"> </i>
          <% end %>
        </td>
      </tr>
  <% end %>
  <tr>
    <td><b>Total</b></td>
    <td><b><%= total %></b></td>
    <td><b></b></td>
  </tr>
  <% @cash_in += total %>
  </tbody>
</table>

app/views/home/_customer_table.html.erb
<table class="table beaccount-table table-responsive table-hover table-striped">
  <thead>
  <tr>
    <th colspan="5">Credit Sale</th>
  </tr>
  <tr>
    <th>Party</th>
    <th>Amount</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @customer_credit_orders.each do |order| %>
      <tr>
        <td>
          <%= order.party.name if order.party.present? %>
        </td>
        <td>
          <%= order.total %>
        </td>
        <td>
          <%= link_to inventory_customers_order_path(order), class: 'btn info-color' do %>
              <i class="fa fa-eye"> </i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/home/_final_balance.html.erb
<div class="col-md-4"></div>
<div class="col-md-4 cal-balance">
  <div class="col-md-12">
    <% if @initial_balance.present? %>
        <div class="col-md-6">
          <h4>Initial Balance</h4>
        </div>
        <div class="col-md-6">
          <h4 class="pull-right"><%= @initial_balance %></h4>
        </div>
    <% else %>
        <div class="col-md-12">
          You hadn't close your previous cash books. To see complete cash book you need to close your previous cash books.
        </div>
    <% end %>
  </div>
  <div class="col-md-12">
    <div class="col-md-6">
      <h4>Cash In</h4>
    </div>
    <div class="col-md-6">
      <h4 class="pull-right"><%= @cash_in %></h4>
    </div>
  </div>
  <div class="col-md-12">
    <div class="col-md-6">
      <h4>Cash Out</h4>
    </div>
    <div class="col-md-6">
      <h4 class="pull-right"><%= @cash_out %></h4>
    </div>
  </div>
  <div class="col-md-12" style="border-top: 1px dashed #d7d7d7">
    <div class="col-md-6">
      <h4>Balance</h4>
    </div>
    <div class="col-md-6">
      <h4 class="pull-right">
        <% if @initial_balance.present? %>
            <%= (@initial_balance + @cash_in) - @cash_out %>
        <% else %>
            <%= @cash_in - @cash_out %>
        <% end %>
      </h4>
    </div>
  </div>
</div>
<div class="col-md-4"></div>

app/views/home/_supplier_payments.html.erb
<table class="table beaccount-table table-responsive table-hover table-striped cashbook-table">
  <thead>
  <tr>
    <th colspan="3">Supplier Payments</th>
  </tr>
  <tr>
    <th>Party</th>
    <th>Amount</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% total = 0.0 %>
  <% @supplier_credit_payments.each do |payment| %>
      <tr>
        <td>
          <%= payment.party.name if payment.party.present? %>
        </td>
        <td>
          <%= payment.total %>
          <% total += payment.total %>
        </td>
        <td>
          <%= link_to inventory_suppliers_payment_path(payment), class: 'btn info-color', remote: true do %>
              <i class="fa fa-eye"> </i>
          <% end %>
        </td>
      </tr>
  <% end %>
  <tr>
    <td><b>Total</b></td>
    <td><b><%= total %></b></td>
    <td><b></b></td>
  </tr>
  <% @cash_out += total %>
  </tbody>
</table>

app/views/home/_supplier_table.html.erb
<table class="table beaccount-table table-responsive table-hover table-striped">
  <thead>
  <tr>
    <th colspan="5">Supplier</th>
  </tr>
  <tr>
    <th>Name</th>
    <th>Amount</th>
    <th>Method</th>
    <th>Type</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @suppliers_data.each do |data| %>
      <tr>
        <td>
          <%= data[:party_name] %>
        </td>
        <td>
          <%= data[:amount] %>
        </td>
        <td>
          <%= data[:method] %>
        </td>
        <td>
          <%= data[:type] %>
        </td>
        <td>
          <%= link_to data[:type] == 'Order' ? inventory_suppliers_order_path(data[:id]) : inventory_suppliers_payment_path(data[:id]), class: 'btn info-color', remote: true do %>
              <i class="fa fa-eye"> </i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/home/cash_book.html.erb
<div class="row reset-padding">
  <div class="content-wrapper">
    <div class="header-wrapper">
      <h4>
        Cash Book (<%= date_format_1(params[:date].present? ? params[:date].to_date : Date.today) %>)
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper">
      <div class="row actions-button">
        <%= form_tag '', method: 'get', id: 'filter-date-range-form' do %>
            <div class="col-sm-3 reset-padding">
              <%= text_field_tag :date, '', value: params[:date].present? ? params[:date] : Date.today, class: 'form-control', id: 'cash_book_date' %>
            </div>
            <div class="col-md-2">
              <%= submit_tag 'Search', class: 'btn btn-default' %>
            </div>
        <% end %>
        <div class="col-md-4">
          <div class="pull-right">
            <% if @initial_balance.present? %>
                <% if @daily_closing.new_record? %>
                    <%= form_for @daily_closing, id: 'daily-closing-form' do |f| %>
                        <%= f.hidden_field :date, value: params[:date].present? ? params[:date] : Date.today, id: 'daily-closing-date' %>
                        <%= f.hidden_field :balance, id: 'daily-closing-balance' %>
                        <%= f.submit 'Close Daily Cash Book', data: { confirm: 'Are you sure you want to close this cash book?' }, class: 'btn btn-primary' %>
                    <% end %>
                <% else %>
                    <%= link_to 'Open Closed Cash Book', daily_closing_path(@daily_closing, date: params[:date].present? ? params[:date] : Date.today), method: :delete, data: {confirm: "Are you sure you want to remove closing information?"}, class: 'btn btn-warning' %>
                <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-md-3">
          <div class="pull-right">
            <% if @is_monthly_closing %>
                <%= link_to 'Close Previous month', close_previous_month_path(month: (@date.beginning_of_month - 1.day).month, year: (@date.beginning_of_month - 1.day).year), data: {confirm: "Are you sure you want to close previous months cash book?"}, class: 'btn btn-info' %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row report-content-body">
        <div class="col-md-3 reset-padding">
          <%= render 'credit_sales' %>
        </div>
        <div class="col-md-3 reset-padding">
          <%= render 'credit_purchases' %>
        </div>
        <div class="col-md-3 reset-padding">
          <%= render 'cash_sales' %>
          <%= render 'customer_payments' %>
        </div>
        <div class="col-md-3 reset-padding">
          <%= render 'cash_outs' %>
          <%= render 'supplier_payments' %>
        </div>
        <div class="col-md-12">
          <%= render 'final_balance' %>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#cash_book_date').datetimepicker({
            format: 'YYYY-MM-DD',
            minDate: '<%= current_department.created_at.strftime('%Y-%m-%d') %>'
        });

        <% if @initial_balance.present? %>
        $('#daily-closing-balance').val('<%= (@initial_balance + @cash_in) - @cash_out %>');
        <% else %>
        $('#daily-closing-balance').val('<%= @cash_in - @cash_out %>');
        <% end %>

    });
</script>

app/views/home/daily_status.html.erb
<div class="row reset-padding">
  <div class="content-wrapper">
    <div class="header-wrapper">
      <h4>
        Daily Status
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper">
      <div class="row actions-button">
        <%= form_tag '', method: 'get', id: 'filter-date' do %>
            <div class="col-sm-3 reset-padding">
              <%= text_field_tag :date, '', value: params[:date].present? ? params[:date] : Date.today, class: 'form-control', id: 'daily_status_date' %>
            </div>
        <% end %>
      </div>
      <div class="row report-content-body">
        <div class="col-md-4 reset-padding">
          <%= render 'supplier_table' %>
        </div>
        <div class="col-md-4 reset-padding">
          <%= render 'customer_table' %>
        </div>
        <div class="col-md-3 reset-padding">
          <table class="table beaccount-table table-responsive table-hover table-striped">
            <thead>
            <tr>
              <th colspan="4">Supplier</th>
            </tr>
            </thead>
            <tbody>
            <% (1..5).each do |i| %>
                <tr>
                  <td>Name</td>
                  <td>Amount</td>
                  <td>Type</td>
                  <td>Actions</td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <div class="col-md-1 reset-padding">
          <table class="table beaccount-table table-responsive table-hover table-striped">
            <thead>
            <tr>
              <th>Balance</th>
            </tr>
            </thead>
            <tbody>
            <% (1..5).each do |i| %>
                <tr>
                  <td>Amount</td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#daily_status_date').datetimepicker({
            format: 'YYYY-MM-DD'
        });
    });
</script>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>