config/routes.rb
Rails.application.routes.draw do

  devise_for :employees

  root 'home#cash_book'

  get '/daily_status', to: 'home#daily_status'
  get '/cash_book', to: 'home#cash_book'
  get '/close_previous_month', to: 'home#close_previous_month'

  resources :daily_closings

  resources :departments do
    get :switch, on: :member
    get :initial_balance, on: :member
    put :update_balance, on: :member
  end

  resources :employees do
    post :add, on: :collection
    put :update_info, on: :member
    get :change_password, on: :member
    put :update_password, on: :member
  end

  namespace :expenses do
    resources :categories
    resources :expenses do
      get :monthly_report, on: :collection
      get :yearly_report, on: :collection
      get :report_breakdown, on: :collection
    end
  end

  namespace :inventory do
    namespace :suppliers do
      resources :suppliers
      resources :orders
      resources :payments
    end
    namespace :customers do
      resources :customers
      resources :orders
      resources :payments
    end
    resources :parties do
      get :balance_report, on: :collection
      post :import, on: :collection
    end
    resources :products do
      get :get_details, on: :member
      get :stock_report, on: :collection
      post :import, on: :collection
    end
    resources :product_categories do
      get :product_sub_categories, on: :member
    end
    resources :deposit_categories
    resources :deposits
    resources :product_replacements do
      get :receive, on: :member
      get :reject_product, on: :member
    end
    resources :withdraw_categories
    resources :withdraws
  end
end

app/models/inventory/base.rb
module Inventory
  class Base < ActiveRecord::Base
    self.abstract_class = true
    self.table_name_prefix = 'inventory_'
  end
end

app/models/inventory/customers/base_customer.rb
module Inventory
  module Customers
    class BaseCustomer < Inventory::Base
      self.abstract_class = true
      self.table_name_prefix = 'inventory_customers_'
    end
  end
end

app/models/inventory/customers/customer.rb
module Inventory
  module Customers
    class Customer < BaseCustomer
      belongs_to :department
    end
  end
end

app/models/inventory/customers/order.rb
module Inventory
  module Customers
    class Order < BaseCustomer
      belongs_to :department
      belongs_to :employee
      belongs_to :party, :class_name => 'Inventory::Party'
      has_one :customers_payment, :class_name => 'Inventory::Customers::Payment', foreign_key: :order_id
      has_many :order_items, :class_name => 'Inventory::Customers::OrderItem'
      after_save :change_party_out_balance
      after_destroy :reset_party_out_balance
      before_save :check_amount_cash, if: -> { customers_payment.present? }
      accepts_nested_attributes_for :customers_payment,:allow_destroy => true,
                                    :reject_if => proc { |attributes| attributes['method'].blank?}
     accepts_nested_attributes_for :order_items,
                                    :allow_destroy => true,
                                    :reject_if => proc {|attributes|
                                      attributes.all? {|k,v| v.blank?}
                                    }

      def change_party_out_balance
        party = Inventory::Party.find_by_id(party_id)
        if total_was.present?
          party.update_attributes(out_balance: (party.out_balance - total_was) + total)
        else
          party.update_attributes(out_balance: party.out_balance + total)
        end
      end

      def reset_party_out_balance
        party = Inventory::Party.find_by_id(party_id)
        party.update_attributes(out_balance: party.out_balance - total)
      end

      def check_amount_cash
        if total == customers_payment.amount
          self.is_cash =  true
          customers_payment.is_cash = true
        end
        customers_payment.employee_id = employee_id
        customers_payment.party_id = party_id
        customers_payment.department_id = department_id
      end

    end
  end
end

app/models/inventory/customers/order_item.rb
module Inventory
  module Customers
    class OrderItem < BaseCustomer
      belongs_to :order, :class_name => 'Inventory::Customers::Order', foreign_key: :order_id
      belongs_to :product, :class_name => 'Inventory::Product'
      after_create :set_product_value
      after_update :change_product_value, if: -> { quantity_changed? }
      after_destroy :reset_product_value

      protected

      def set_product_value
        product = Inventory::Product.find_by_id(product_id)
        qt = quantity.present? ? product.quantity - quantity : product.quantity
        product.update_attributes(quantity: qt)
      end

      def change_product_value
        product = Inventory::Product.find_by_id(product_id)
        qt = quantity_changed? && quantity.present? ? product.quantity - (quantity - quantity_was) : product.quantity
        product.update_attributes(quantity: qt)
      end

      def reset_product_value
        product = Inventory::Product.find_by_id(product_id)
        qt = product.quantity + quantity
        product.update_attributes(quantity: qt)
      end
    end
  end
end

app/models/inventory/customers/payment.rb
module Inventory
  module Customers
    class Payment < Inventory::Customers::BaseCustomer
      belongs_to :department
      belongs_to :party, :class_name => 'Inventory::Party'
      belongs_to :employee
      belongs_to :sales_order, :class_name => 'Inventory::Customers::Order', foreign_key: :order_id
      before_save :set_total
      after_save :change_party_out_balance
      after_destroy :reset_party_out_balance

      protected

      def set_total
        if amount.present? && !total.present?
          self.total = amount
        end
      end

      def change_party_out_balance
        party = Inventory::Party.find_by_id(party_id)
        if amount_was.present?
          party.update_attributes(out_balance: (party.out_balance + amount_was) - amount)
        else
          party.update_attributes(out_balance: party.out_balance - amount)
        end
      end

      def reset_party_out_balance
        party = Inventory::Party.find_by_id(party_id)
        party.update_attributes(out_balance: party.out_balance + amount)
      end
    end
  end
end

app/models/inventory/deposit.rb
module Inventory
  class Deposit < Base
    belongs_to :department
    belongs_to :deposit_category, :class_name => 'Inventory::DepositCategory'
  end
end

app/models/inventory/deposit_category.rb
module Inventory
  class DepositCategory < Base
    belongs_to :department
    has_many :deposits, :class_name => 'Inventory::Deposit'
  end
end

app/models/inventory/party.rb
module Inventory
  class Party < Base
    belongs_to :department
    has_many :purchase_orders, :class_name => 'Inventory::Suppliers::Order'
    has_many :suppliers_payments, :class_name => 'Inventory::Suppliers::Payment'
    has_many :customers_payments, :class_name => 'Inventory::Customers::Payment'
    has_many :product_replacements, :class_name => 'Inventory::ProductReplacement'
    has_many :parties_monthly_closings

    def created_date
      self.created_at.present? ? self.created_at.strftime('%Y-%m-%d').to_date : Date.today
    end

    def self.active
      self.where(is_active: true)
    end

    def self.import(current_department, file)
      spreadsheet = Roo::Spreadsheet.open(file.path)
      header = spreadsheet.row(1)
      header[6] = 'initial_in_balance'
      header[7] = 'initial_out_balance'
      puts header.inspect

      (2..spreadsheet.last_row).each do |i|
        item = spreadsheet.row(i)
        item[6] = 0 unless item[6].present?
        item[7] = 0 unless item[7].present?
        row = Hash[[header, item].transpose]
        party = new
        party.attributes = row.to_hash
        party.department_id = current_department.id
        party.save!
      end
    end

    def self.history(current_department, party_id, start_date, end_date)
      history = []
      history = purchase_order_history(history, current_department, party_id, start_date, end_date)
      history = sales_order_history(history, current_department, party_id, start_date, end_date)
      history = supplier_payment_history(history, current_department, party_id, start_date, end_date)
      history = customer_payment_history(history, current_department, party_id, start_date, end_date)
      history.sort_by! {|hist| hist[:date]}
    end

    def self.purchase_order_history(history, current_department, party_id, start_date, end_date)
      purchase_orders = current_department.purchase_orders.where(party_id: party_id, date: start_date..end_date).includes(:party)
      purchase_orders.each do |order|
        history.push({party: order.party.name, type: 'Purchase order', amount_plus: order.total, amount_minus: 0, date: order.created_at})
      end
      history
    end

    def self.sales_order_history(history, current_department, party_id, start_date, end_date)
      sales_orders = current_department.sale_orders.where(party_id: party_id, date: start_date..end_date).includes(:party)
      sales_orders.each do |order|
        history.push({party: order.party.name, type: 'Sale order', amount_plus: 0, amount_minus: order.total, date: order.created_at})
      end
      history
    end

    def self.supplier_payment_history(history, current_department, party_id, start_date, end_date)
      payments = current_department.suppliers_payments.where(party_id: party_id, date: start_date..end_date).includes(:party)
      payments.each do |payment|
        history.push({party: payment.party.name, type: 'Payment Given', amount_plus: 0, amount_minus: payment.amount, date: payment.created_at})
      end
      history
    end

    def self.customer_payment_history(history, current_department, party_id, start_date, end_date)
      payments = current_department.customers_payments.where(party_id: party_id, date: start_date..end_date).includes(:party)
      payments.each do |payment|
        history.push({party: payment.party.name, type: 'Payment Received', amount_plus: payment.amount, amount_minus: 0, date: payment.created_at})
      end
      history
    end
  end
end

app/models/inventory/product.rb
module Inventory
  class Product < Base
    belongs_to :department
    belongs_to :category, :class_name => 'Inventory::ProductCategory', foreign_key: :category_id
    belongs_to :sub_category, :class_name => 'Inventory::ProductCategory', foreign_key: :sub_category_id
    has_many :product_replacements, :class_name => 'Inventory::ProductReplacement'
    has_many :customers_order_items, :class_name => 'Inventory::Customers::OrderItem'
    has_many :suppliers_order_items, :class_name => 'Inventory::Suppliers::OrderItem'
    has_many :products_monthly_closings

    before_save :set_initial_balance

    def created_date
      self.created_at.present? ? self.created_at.strftime('%Y-%m-%d').to_date : Date.today
    end

    def self.history(current_department, product_id, start_date, end_date)
      history = []
      history = purchase_order_history(history, current_department, product_id, start_date, end_date)
      history = sales_order_history(history, current_department, product_id, start_date, end_date)
      history = replacement_history(history, current_department, product_id, start_date, end_date)
      history.sort_by! {|hist| hist[:date]}
    end

    def self.purchase_order_history(history, current_department, product_id, start_date, end_date)
      purchase_order_items = Inventory::Suppliers::OrderItem.where(product_id: product_id).includes(:order).includes(:product).where('inventory_suppliers_orders.department_id = ? AND inventory_suppliers_orders.date IN (?)', current_department.id, start_date..end_date).references(:inventory_suppliers_orders)
      purchase_order_items.each do |order_item|
        #total_in += order_item.quantity
        history.push({product: order_item.product.name, type: 'Purchase order', in: order_item.quantity, out: 0, date: order_item.order.date})
      end
      history
    end

    def self.sales_order_history(history, current_department, product_id, start_date, end_date)
      sales_order_items = Inventory::Customers::OrderItem.where(product_id: product_id).includes(:order).includes(:product).where('inventory_customers_orders.department_id = ? AND inventory_customers_orders.date IN (?)', current_department.id, start_date..end_date).references(:inventory_customers_orders)
      sales_order_items.each do |order_item|
        #total_out += order_item.quantity
        history.push({product: order_item.product.name, type: 'Sales order', in: 0, out: order_item.quantity, date: order_item.order.date})
      end
      history
    end

    def self.replacement_history(history, current_department, product_id, start_date, end_date)
      replacements = current_department.product_replacements.where(product_id: product_id).includes(:product).where(date: start_date..end_date)

      replacements.each do |replacement|
        #total_out += replacement.quantity
        history.push({product: replacement.product.name, type: 'Replacement', in: 0, out: replacement.quantity, date: replacement.date})
        if replacement.receive_date.present? && replacement.receive_date.between?(start_date, end_date)
          #total_in += replacement.quantity
          history.push({product: replacement.product.name, type: 'Replacement received', in: replacement.quantity, out: 0, date: replacement.date})
        end
      end
      history
    end

    def self.import(file)
      spreadsheet = Roo::Spreadsheet.open(file.path)
      header = spreadsheet.row(1)
      header.delete_at(2)
      header.delete_at(2)
      (2..spreadsheet.last_row).each do |i|
        item = spreadsheet.row(i)
        item_full = spreadsheet.row(i)
        item[4] = 0 unless item[4].present?
        item[5] = 0 unless item[5].present?
        item.delete_at(2)
        item.delete_at(2)

        row = Hash[[header, item].transpose]
        product = new
        product.attributes = row.to_hash
        dept = Department.first
        product.department_id = dept.id
        product_category = Inventory::ProductCategory.find_or_initialize_by(name: item_full[2])
        if product_category.new_record?
          product_category.department_id = dept.id
          product_category.save!
        end

        product.category_id = product_category.id
        if item_full[3].present? && item_full[3].size > 0
          product_sub_category = Inventory::ProductCategory.find_or_initialize_by(name: item_full[3])
          if product_sub_category.new_record?
            product_sub_category.category_id = product_category.id
            product_sub_category.department_id = dept.id
            product_sub_category.save!
          end
          product.sub_category_id = product_sub_category.id
        end
        product.save!
      end
    end

    protected

    def set_initial_balance
      if quantity.present?
        self.initial_quantity = quantity
      end
    end
  end
end

app/models/inventory/product_category.rb
module Inventory
  class ProductCategory < Base
    belongs_to :department
    has_many :sub_categories, :class_name => 'Inventory::ProductCategory', foreign_key: :category_id
    belongs_to :category, :class_name => 'Inventory::ProductCategory', foreign_key: :category_id
    has_many :products, :class_name => 'Inventory::Product', foreign_key: :category_id
    has_many :sub_products, :class_name => 'Inventory::Product', foreign_key: :sub_category_id

    def self.get_all(current_department)
      current_department.product_categories.where(category_id: nil)
    end

    def self.sub_categories(category_id)
      where(category_id: category_id)
    end
  end
end

app/models/inventory/product_replacement.rb
module Inventory
  class ProductReplacement < Inventory::Base
    belongs_to :department
    belongs_to :party, :class_name => 'Inventory::Party'
    belongs_to :product, :class_name => 'Inventory::Product'
    after_save :change_product_quantity
    after_destroy :reset_product_quantity

    protected

    def change_product_quantity
      product = Inventory::Product.find_by_id(party_id)
      if quantity_was.present?
        if quantity_changed?
          product.update_attributes(quantity: (product.quantity + quantity_was) - quantity)
        end
      else
        product.update_attributes(quantity: product.quantity - quantity)
      end
    end

    def reset_product_quantity
      product = Inventory::Product.find_by_id(party_id)
      product.update_attributes(quantity: product.quantity + quantity)
    end
  end
end

app/models/inventory/suppliers/base_supplier.rb
module Inventory
  module Suppliers
    class BaseSupplier < Inventory::Base
      self.abstract_class = true
      self.table_name_prefix = 'inventory_suppliers_'
    end
  end
end

app/models/inventory/suppliers/supplier.rb
module Inventory
  module Suppliers
    class Supplier < BaseSupplier
      belongs_to :department
      has_many :orders, :class_name => 'Inventory::Suppliers::Order'

      def self.active
        self.where(is_active: true)
      end
    end
  end
end

app/models/inventory/withdraw.rb
module Inventory
  class Withdraw < Inventory::Base
    belongs_to :department
    belongs_to :withdraw_category, :class_name => 'Inventory::WithdrawCategory'
  end
end

app/models/inventory/withdraw_category.rb
module Inventory
  class WithdrawCategory < Inventory::Base
    belongs_to :department
    has_many :withdraws, :class_name => 'Inventory::Withdraw'
  end
end

app/controllers/inventory/base_controller.rb
module Inventory
  class BaseController < ApplicationController

  end
end

app/views/inventory/product_replacements/_form.html.erb
<%= form_for @product_replacement,  html:{id: 'product-replacement-form'} do |f| %>
    <div class="col-md-12 reset-padding">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :product_id, 'Product' %>
          <%= f.select :product_id, options_for_select(Inventory::Product.all.collect{ |product| [product.name, product.id]}, f.object.product_id), {prompt: "Select Product..."}, {class:'form-control custom-chosen replacement-product-select'}  %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :party_id, 'Send To' %>
          <%= f.select :party_id, options_for_select(Inventory::Party.active.collect{ |party| [party.name, party.id]}, f.object.party_id), {prompt: "Select Party..."}, {class:'form-control custom-chosen', id: 'replacement-party-select'}  %>
        </div>
      </div>
    </div>
    <div class="col-md-12 reset-padding">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :quantity %>
          <%= f.text_field :quantity, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :date %>
          <%= f.text_field :date, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="col-md-12 reset-padding">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :tracking_no %>
          <%= f.text_field :tracking_no, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :note %>
          <%= f.text_area :note, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="pull-right">
        <%= f.submit @product_replacement.new_record? ? 'Create Replacement Order' : 'Update Replacement Order', class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>


<script type="text/javascript">
  $(function(){
      $('#inventory_product_replacement_date').datetimepicker({
          format: 'YYYY-MM-DD'
      });
  });
</script>

app/views/inventory/product_replacements/_replacement_detail.html.erb
<%= render 'shared/modal_header', title: 'Product Replacement Detail' %>

<div class="modal-body">
  <h4>Product Name</h4>
  <%= @product_replacement.product.name %>
  <h4>Product Quantity</h4>
  <%= @product_replacement.quantity %>
  <h4>Send To</h4>
  <%= @product_replacement.party.name if @product_replacement.party.present? %>
  <h4>Date</h4>
  <%= date_format_1 @product_replacement.date %>
  <% if @product_replacement.receive_date.present? %>
      <h4>Status</h4>
      <%= 'Replaced' %>
      <h4>Receive Date</h4>
      <%= date_format_1 @product_replacement.receive_date %>
  <% else %>
      <h4>Status</h4>
      <%= 'Pending' %>
  <% end %>
  <h4>Note</h4>
  <%= @product_replacement.note %>
</div>

<div class="modal-footer clearfix">
  <div class="pull-right">
    <div class='btn btn-default' data-dismiss="modal">Close</div>
  </div>
</div>

app/views/inventory/product_replacements/_replacement_row.html.erb
<tr>
  <td><%= product_replacement.product.name %></td>
  <td><%= product_replacement.tracking_no %></td>
  <td><%= product_replacement.quantity %></td>
  <td><%= product_replacement.party.name if product_replacement.party.present? %></td>
  <td><%= date_format_1 product_replacement.date %></td>
  <td><%= date_format_1 product_replacement.receive_date %></td>
  <td><%= product_replacement.receive_date.present? ? 'Replaced' : 'Pending' %></td>
  <td>
    <% if product_replacement.receive_date.present? %>
        <%= link_to 'reject', reject_product_inventory_product_replacement_path(product_replacement), data: {confirm: "Are you sure you want to reject the replacement?"} %>
    <% else %>
        <%= link_to 'receive', receive_inventory_product_replacement_path(product_replacement), data: {confirm: "Are you sure you want to receive the replacement?"} %>
    <% end %>
    <%= link_to inventory_product_replacement_path(product_replacement), class: 'btn info-color', remote: true do %>
        <i class="fa fa-eye"> </i>
    <% end %>
    <%= link_to edit_inventory_product_replacement_path(product_replacement), class: 'btn warning-color' do %>
        <i class="fa fa-pencil"> </i>
    <% end %>
    <%= link_to inventory_product_replacement_path(product_replacement), method: :delete, class: 'btn danger-color', data: {confirm: "Are you sure?"} do %>
        <i class="fa fa-times"> </i>
    <% end %>
  </td>
</tr>

app/views/inventory/product_replacements/edit.html.erb
<div class="row reset-padding">
  <div class="content-wrapper">
    <div class="header-wrapper">
      <h4>
        Edit Replacement Order
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper">
      <div class="row content-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/inventory/product_replacements/index.html.erb
<div class="row reset-padding">
  <div class="content-wrapper">
    <div class="header-wrapper">
      <h4>
        Product Replacements
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper">
      <div class="row actions-button">
        <div class="col-md-6 reset-padding">
          <%= form_tag '', method: 'get', id: 'daterange-withdraws-form' do %>
              <%= text_field_tag :daterange, '', value: params[:daterange], class: 'form-control' %>
          <% end %>
        </div>
        <div class="col-md-6 reset-padding">
          <%= link_to new_inventory_product_replacement_path, class: 'btn btn-default pull-right' do %>
              <i class="fa fa-plus-circle"></i> Create Product Replacement
          <% end %>
        </div>
      </div>
      <div class="row content-body">
        <table id="replacement" class="searchable-table table beaccount-table action-table table-responsive table-hover table-striped">
          <thead>
          <tr>
            <th>Product Name</th>
            <th>Tracking No</th>
            <th>Product Quantity</th>
            <th>Send To</th>
            <th>Date</th>
            <th>Rcv Date</th>
            <th>Status</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @product_replacements.each do |replacement| %>
              <%= render 'replacement_row', product_replacement: replacement %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
    $('#replacement').DataTable({
        "bSort": false,
        "paginationType": "bootstrap",
        "pagingType": "full_numbers",
        "sPaginationType": "bootstrap"
    });

    var options = {
        showDropdowns: true,
        locale: {
            format: 'YYYY-MM-DD',
            separator: ' To '
        }
    };
    $(function () {
        if (!<%= params[:daterange].present? %>) {
            options.startDate = "<%= Date.today.beginning_of_month %>";
            options.endDate = "<%= Date.today.end_of_month %>";
        }

        $('#daterange').daterangepicker(options).on('apply.daterangepicker', function (ev, picker) {
            $('#daterange-withdraws-form').submit();
        });
    });
    });
</script>

app/views/inventory/product_replacements/new.html.erb
<div class="row reset-padding">
  <div class="content-wrapper">
    <div class="header-wrapper">
      <h4>
        New Replacement Order
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper">
      <div class="row content-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/inventory/product_replacements/show.js.erb
$('#global-modal').modal('show').find('.modal-content').html("<%= escape_javascript(render 'replacement_detail').html_safe %>");